# @package ml
# Default ML configuration
# Balanced settings for general use

batch_size: null  # Auto-determined based on available memory
learning_rate: 1e-4
model_cache_size: 3
checkpoint_frequency: 100
gradient_accumulation_steps: 1
max_grad_norm: 1.0
warmup_steps: 0
weight_decay: 0.01
enable_gradient_checkpointing: false